colors = ["red", "grren", "blue", "aqua", "indigo", "violet", "brown", "black"]
num = [1, 5, 37, 3, 7, 37, 88, 844, 43, 67, 22]
# print(colors)
# print(num)
# print(colors.index("aqua"))
# print(num.index(37))
# colors.sort()
# num.sort()
# print(colors)
# print(num)
# colors.sort(reverse=True)
# num.sort(reverse=True)
# print(colors)
# print(num)
# colors.reverse()
# num.reverse()
# print(colors)
# print(num)
# print(colors.index("aqua"))
# print(num.index(37))
# print(num.count(37))
# col = colors.copy()
# print(col)
# colors.append("pink")
# colors.insert(1, "pink")
ucolo = ["pink", "white"]
# colors.extend(ucolo)
colours = colors + ucolo + num
print(colors)
print(colours)
