cities = {"Delhi", "Dhaka", "Kathmandu", "Tokyo", "Punakha", "Lhasa"}
cities2 = {"WashingtonDC", "Ontario", "MexicoCity", "Delhi", "Tokyo", "Moscow"}
cities3 = {"Delhi", "Kathmandu", "Tokyo"}
# cities3 = cities.union(cities2)
# print(cities3)
# cities.update(cities2)
# print(cities)
# cities3 = cities.intersection(cities2)
# print(cities3)
# cities.intersection_update(cities2)
# print(cities)
# cities3 = cities.symmetric_difference(cities2)
# print(cities3)
# cities.symmetric_difference_update(cities2)
# print(cities)
# cities3 = cities.difference(cities2)
# print(cities3)
# cities.difference_update(cities2)
# print(cities)
# print(cities.isdisjoint(cities2))
# print(cities.issuperset(cities3))
# print(cities3.issubset(cities))
# cities.add("Helsinki")
# print(cities)
# cities.remove("Tokyo")
# print(cities)
# cities.discard("Dhaka")
# print(cities)
# cities.remove("Toky")
# print(cities)
# cities.discard("Dhka")
# print(cities)
# item = cities.pop()
# print(cities, item, sep="||")
# del cities
# print(cities)
# cities.clear()
# print(cities)
# if "Delhi" in cities:
#     print("Yup!")
# else:
#     print("Noo!")
cities4 = cities.copy()
print(cities4)
