# a = input()
# print("My name is", a)
# a = input("Enter your name : ")
# print("My name is", a)
# x = input("Enter your first no. :")
# y = input("Enter your second no. :")
# print(x + y)
x = int(input("Enter your first no. : "))
y = int(input("Enter your second no. : "))
print(x + y)
